### ISSUE TITLE
Native Ad Image Icon + Main FameLayout Image/Video not Loaded 

### ISSUE THREAD

**Issue by tr-appz** [AppLovin/AppLovin-MAX-SDK-Android#297]
The Applovin MAX Native ads are filled but the Both Image i.e Icon + Main Image is Not Loaded in Native Template .

The Main Image is not loading in Applovin MAX MEDIUM NATIVE Ad, in MEDIUM Native Image Icons is loaded but not the main Image inside the FrameLayout.

I have implemented both Manual Template native Ads & The Default Medium Provided By Applovin . I am writing this after research, I have tried & fixed these following problems.

I was using MEDIUM Native Code in Manual Template (Fixed Ad Unit BUT Still Same Issue)
Test Mode was enabled & Came to know test mode may be the problem. ( Tested on my 3rd Device, which is not added as test device, BUT Still same issue)
In Manual Native Ads BOTH Image Icons & main Image is not showing. & In Default MEDIUM Ad unit Image icons is showing but not the main image. ( Same Problem in both Applovin Test Mode & FB Test Mode & Non Test Mode)

Applovin SDK : 11.3.2

Kindly, Help me with the solution.

**Comment by santoshbagadi** [comment]
Hi @tr-appz , do you by any chance use `warp_content` for the container view when adding the native template ad view to the view-hierarchy. You may want to set a fixed height to the native ad view for medium templates to be rendered correctly. 

If you are using native manual and see that the icon and image are not rendering, please make sure that you are using an ad unit ID whose template is set to `Manual`. We've fixed test mode issues for native manual as well, but we do require a valid manual native ad unit ID for test mode to work.

If you are still facing the issue, could you please provide [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) when the issue is occurring.

**Comment by tr-appz** [comment]
@santoshbagadi  UPDATE : I tried changing that CardView height to specifically 355dp. So now The main Image started rendering in the Non-Manual Ad Placement i.e the MEDIUM Ad UNIT.  

But the problem is still the same in case of manual template Native Ad Setup. Still Both the Images are not rendering.

BTW, one more thing... Is there any way to change color of the MEDIUM Native Ad which is setup wthout template just by applovin's default template.


Here's Both XMLs

native_ad_template.xml
`<androidx.constraintlayout.widget.ConstraintLayout android:layout_width="match_parent"
    android:layout_height="355dp"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    app:layout_constraintBottom_toBottomOf="parent"
    android:layout_centerInParent="true"
    android:padding="5dp"
    android:maxHeight="355dp"
    android:id="@+id/background"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <FrameLayout
        android:id="@+id/media_view_container"
        android:layout_margin="@dimen/gnt_no_size"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_marginTop="@dimen/gnt_no_margin"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toTopOf="@id/middle"
        />

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_height="60dp"
        android:layout_marginTop="@dimen/gnt_default_margin"
        android:layout_width="match_parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/media_view_container"
        app:layout_constraintBottom_toTopOf="@+id/body_text_view"
        android:id="@+id/middle"
        >
        <androidx.constraintlayout.widget.ConstraintLayout

            android:layout_width="@dimen/gnt_no_size"
            android:layout_height="@dimen/gnt_no_size"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:orientation="horizontal"
            >
            <ImageView
                android:id="@+id/icon_image_view"
                android:layout_width="0dp"
                android:layout_weight="0"
                android:layout_height="match_parent"
                android:layout_marginTop="@dimen/gnt_no_margin"
                android:layout_marginStart="@dimen/gnt_default_margin"
                android:layout_marginBottom="@dimen/gnt_no_margin"
                android:layout_marginEnd="@dimen/gnt_no_margin"
                app:layout_constraintDimensionRatio="H,1:1"
                android:scaleType="fitCenter"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@id/content"
                />
            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="@dimen/gnt_no_size"
                android:layout_height="@dimen/gnt_no_size"
                android:orientation="vertical"
                android:id="@+id/content"
                android:layout_marginLeft="@dimen/gnt_default_margin"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintStart_toEndOf="@id/icon_image_view"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                >
                <LinearLayout
                    android:id="@+id/linear_layout_maxn"
                    android:orientation="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/gnt_no_size"
                    android:layout_weight="0.5"
                    app:layout_constraintBottom_toTopOf="@+id/row_two"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    >

                    <TextView
                        android:id="@+id/title_text_view"
                        android:background="@color/gnt_white"
                        android:textStyle="bold"
                        android:textSize="@dimen/gnt_text_size_large"
                        android:textColor="@color/gnt_gray"
                        android:lines="1"
                        android:layout_height="match_parent"
                        android:layout_width="match_parent"
                        android:layout_marginTop="@dimen/gnt_no_margin"
                        android:layout_marginBottom="@dimen/gnt_no_margin"
                        android:layout_marginStart="@dimen/gnt_no_margin"
                        android:layout_marginEnd="@dimen/gnt_no_margin"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toEndOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        />
                </LinearLayout>
                <LinearLayout
                    android:id="@+id/row_two"
                    android:orientation="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/gnt_no_size"
                    android:layout_weight="0.5"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@id/linear_layout_maxn"
                    >
                    <TextView
                        android:background="@drawable/gnt_rounded_corners_shape"
                        android:layout_width="@dimen/gnt_ad_indicator_width"
                        android:gravity="center"
                        android:id="@+id/ad_notification_view"
                        android:layout_height="@dimen/gnt_ad_indicator_height"
                        android:layout_marginTop="@dimen/gnt_ad_indicator_top_margin"
                        android:layout_marginStart="@dimen/gnt_no_margin"
                        android:layout_marginEnd="@dimen/gnt_default_margin"
                        android:text="Ad"
                        android:textColor="@color/gnt_ad_green"
                        android:textStyle="bold"
                        android:textSize="@dimen/gnt_ad_indicator_text_size"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        >
                    </TextView>

                    <TextView
                        android:id="@+id/advertiser_textView"
                        android:background="@color/gnt_white"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:gravity="top"
                        android:textSize="@dimen/gnt_text_size_small"
                        android:textColor="@color/gnt_gray"
                        android:lines="1"
                        android:layout_marginTop="@dimen/gnt_no_margin"
                        android:layout_marginBottom="@dimen/gnt_no_margin"
                        android:layout_marginStart="@dimen/gnt_no_margin"
                        android:layout_marginEnd="@dimen/gnt_no_margin"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toEndOf="@id/ad_notification_view"
                        app:layout_constraintTop_toTopOf="parent"
                        />

                </LinearLayout>


            </androidx.constraintlayout.widget.ConstraintLayout>


        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.constraintlayout.widget.ConstraintLayout>
    <TextView
        android:layout_width="match_parent"
        android:layout_margin="@dimen/gnt_no_size"
        android:layout_height="wrap_content"
        android:paddingBottom="@dimen/gnt_default_margin"
        android:paddingLeft="@dimen/gnt_default_margin"
        android:id="@+id/body_text_view"
        app:layout_constraintBottom_toTopOf="@+id/cta_button"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/middle"
        android:layout_marginBottom="@dimen/gnt_default_margin"
        />
    <Button
        android:id="@+id/cta_button"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:background="@color/gnt_blue"
        android:textColor="@color/gnt_white"
        android:layout_marginLeft="5dp"
        android:layout_marginRight="5dp"
        android:lines="1"
        android:gravity="center"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/body_text_view"
        />

</androidx.constraintlayout.widget.ConstraintLayout>`


Now, here's the in Container XML

`<LinearLayout
            android:layout_marginTop="3dp"
            android:layout_width="match_parent"
            android:layout_height="355dp"
            android:id="@+id/native_ad_layout"
            android:visibility="gone"
            android:orientation="vertical">

            <androidx.cardview.widget.CardView
                android:layout_width="match_parent"
                android:id="@+id/nativeAdViewHome"
                android:layout_height="wrap_content"
                android:layout_marginRight="10dp"
                android:layout_marginLeft="10dp"
                app:cardCornerRadius="8dp">

                <my.app.package.TemplateView
                    android:id="@+id/home_template"
                    app:gnt_template_type="@layout/gnt_medium_template_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content" />
            </androidx.cardview.widget.CardView>

        </LinearLayout>`

Using native_ad_layout as the container.



Let me Know Where I am wrong, So that we can fix this issue.

**Comment by tr-appz** [comment]
@santoshbagadi  I know this will be off topic BUT How can we disable Banner Ads Auto Refresh & Native Ads in Auto Refresh in Recycler View. As I suspect that due to too frequent refreshes Facebook Bidding is not responding to the requests.

**Comment by tr-appz** [comment]
@santoshbagadi , Now even i don't like to mention you again and again. as it feels like spam but there's no response so i have to do it. Kindly Anyone from the Applovin Team Please fix these issue of FB Bidding & Native Ads.

**Comment by santoshbagadi** [comment]
@tr-appz sorry for the delayed response. For disabling banner refresh, you can call `MaxAdView.stopAutoRefresh()`. 

For the native manual icon and media view not rendering, it might be a delay after the setting has been changed on the dashboard. If you are not doing so already, I would suggest creating separate Ad Units for manual and template ads and test them to see if the issue still occurs. 

For FB bidding, if you are getting test ads, that means the integration looks good. If you are not able to get live fill from FB, there could be multiple reasons. Generally FB does not fill on devices that do not have FB app installed with a valid FB account logged in.

**Comment by tr-appz** [comment]
> For FB bidding, if you are getting test ads, that means the integration looks good. If you are not able to get live fill from FB, there could be multiple reasons. Generally FB does not fill on devices that do not have FB app installed with a valid FB account logged in.

@santoshbagadi 

We already knew it as we have integrated FB with other ad network before also. That's not the reason. & one more thing that suspect is that in my FB dashboard i have set FB to use real advertiser ads even in test mode. BUT Applovin  is showing just FB Test Ads only which are not real advertiser ads.


Sad to say but this made me thinking Applovin does not perform bidding in LIVE mode and just it's own ads.

**Comment by tr-appz** [comment]
@santoshbagadi  Thanks for your assistance, We have used Applovin Default Medium Native Instead.

Now, Sir We are receiving FB ads on one Native Ad Unit but not on other. So can you please guide us about what we are doing wrong.

We have checked that in Applovin Dash Ad-Unit is MEDIUM and Meta bidding is enabled with Placement added.

**Comment by williamycyh** [comment]
I encountered the same problem, there is no big image and small image when adding manually. 
Applovin  Default Medium Native is ok.
it can't be show even i use the Default Medium Native layout exactly the same on my manual layout.
@santoshbagadi @tr-appz pls help

**Comment by santoshbagadi** [comment]
@tr-appz could you please share your account email to further investigate.

@williamycyh could you double check that you have `Custom` selected as the `Template` in your dashboard for the ad unit ID. You should ideally create separate ad unit IDs for Medium template and Custom template to test.

**Comment by tr-appz** [comment]
> @tr-appz could you please share your account email to further investigate.

Applovin Email : rakshak2809@gmail.com

**Comment by tr-appz** [comment]
@santoshbagadi  Please if you can then please make you support somewhat faster as due to that Native Ad not showing FB Ads, we are making a lot of unrealized loss on daily basis + applovin shows a lot vulgar ads which harm the user experience a lot. and resist users to open the app in Open due to those ads.

**Comment by santoshbagadi** [comment]
@tr-appz , I've checked all 4 ad units, and I'm just mostly seeing no-bids from FB. So, you should reach out to your Facebook contact to see why they might not be bidding.
